apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170987667
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170987667
    app.kubernetes.io/part-of: test-app-170987667
  name: python-basic-170987667
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-170987667
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-170987667
    spec:
      containers:
      - image: quay.io/hacdev/pyaqwvfr-tenant/test-app-170987667/python-basic-170987667@sha256:51b47f383e4d7311c86a10ee152ca3967f85e162e6db007c69990262959ab98d
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
